FROM node:23-alpine

# Install pnpm globally
RUN npm install -g pnpm

# Create and set the working directory
WORKDIR /app

COPY . .

# Install dependencies
RUN pnpm install

# Expose the port used by Vite
EXPOSE 5173

# Start the development server
CMD ["pnpm", "run", "devContainer"]
